autoInstallPeers: false
allowBuilds:
  '@google/genai': false
  protobufjs: false
minimumReleaseAgeExclude:
  - '@earendil-works/pi-agent-core@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@earendil-works/pi-ai@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@earendil-works/pi-client@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@earendil-works/pi-coding-agent@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@earendil-works/pi-protocol@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@earendil-works/pi-telemetry@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@earendil-works/pi-tui@0.84.0 || 0.84.1 || 0.84.2 || 0.84.3 || 0.84.4'
  - '@agentclientprotocol/claude-agent-acp@0.65.0 || 0.66.0 || 0.67.0 || 0.68.0 || 0.69.0 || 0.70.0 || 0.71.0 || 0.72.0 || 0.73.0'
  - '@anthropic-ai/claude-agent-sdk-darwin-arm64@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-darwin-x64@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64-musl@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-linux-arm64@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-linux-x64-musl@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-linux-x64@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-win32-arm64@0.3.257'
  - '@anthropic-ai/claude-agent-sdk-win32-x64@0.3.257'
  - '@anthropic-ai/claude-agent-sdk@0.3.257'
